@host = https://phonebook-jd2m.onrender.com/api/persons/

### Test the all persons endpoint
GET {{host}}

### Test the all persons endpoint
GET {{host}}/6a4c473d44e66fc8b7dd9d8

### Test the wrong endpoint
GET https://phonebook-jd2m.onrender.com/api/perso

### 
POST {{host}}
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-456-7890"
}

### Test the updating a person
PUT {{host}}6a4dab1a74ee82bb3264ba3e
Content-Type: application/json

{
  "name": "John Doe",
  "number": "111-111-1111"
}

### Test deleting a person
DELETE {{host}}6a4da8502b4e0b53606eebf8