### Test the all persons endpoint
GET http://localhost:3001/api/persons

### Test the all persons endpoint
GET http://localhost:3001/api/persons/2

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-456-7890"
}

### Test deleting a person
DELETE http://localhost:3001/api/persons/314751

### Test the all persons endpoint
GET http://localhost:3001/api/perso